spring:
  data:
    mongodb:
      username: test
      password: test
      database: vulndb
      port: 27017
      host: localhost
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
